### ISSUE TITLE
后面会提供playground吗

### ISSUE THREAD

**Issue by QiQingY** [OpenSPG/openspg#20]
请问可以提供一个playground吗？能够快速在产品层面适用下，体验下openspg在KG的各个阶段的功能及对比其他框架的优势。现在文档内容过多，感觉跑一个demo的学习成本都比较高。

因为本身openspg这个概念也是一个很新的东西，希望在了解底层及代码逻辑之前，能够在应用层上有体感~~

最后点赞下openspg，确实是个非常不错的东西，持续学习中~

**Comment by zhangcongxiao** [comment]
学冒烟了，感觉文档写的太简单了，很不好理解

**Comment by baifuyu** [comment]
> 学冒烟了，感觉文档写的太简单了，很不好理解

(。・＿・。)ﾉI’m sorry~，目前确实门槛还有点高，有些概念比较难理解，我们会持续优化改进。欢迎一起讨论优化下文档

**Comment by baifuyu** [comment]
> 学冒烟了，感觉文档写的太简单了，很不好理解

非常感谢您对 OpenSPG 的关注和问题反馈，OpenSPG刚刚开源不久，我们也在持续完善文档和功能。也欢迎您提供更具体的反馈，我们可以更快更准确地解决您的问题，也欢迎您参与到项目的社区共建中来。
构建企业级的语义框架和知识引擎，持续降低领域图谱的落地门槛和迁移成本是OpenSPG持续坚持的方向。近期我们也将发布构建原则和最佳实践，以减少用户理解成本，欢迎关注OpenSPG的发布动态， 我们将第一时间通知，再次表达感谢。

--
Thank you very much for your interest in OpenSPG and for providing feedback. OpenSPG has only recently become open-source, and we are continuously improving our documentation and features. We welcome you to provide more specific feedback so that we can address your concerns more quickly and accurately. You are also invited to participate in the community co-building of the project.

Our ongoing commitment with OpenSPG is to build enterprise-level semantic frameworks and knowledge engines, while consistently working to lower the barriers to implementation and the costs of transitioning for domain knowledge graphs. In the near future, we will also release construction principles and best practices to reduce the learning curve for our users. Please stay tuned for the latest updates from OpenSPG; we will notify you as soon as they are available. Thank you once again.
