### ISSUE TITLE
java 版本

### ISSUE THREAD

**Issue by yezhoujie** [OpenSPG/openspg#418]
pom中设置的java版本为1.8，
```
<java.version>1.8</java.version>
```
能升级到新版java 版本么？

**Comment by bader1000** [comment]
Rechtbank

**Comment by bader1000** [comment]
> طوبا ل 1.8،
> 
> ```
> <java.version>1.8</java.version>
> ```
> 
> 能升级到新版java 版本么？

**Comment by bader1000** [comment]
The Financial Exploitation I Am Experiencing:
1. Individuals or Parties Responsible for the Exploitation:

Primary Party: My cousin, who falsely claims to be a partner in my companies (e.g., "Al-Malik") without any legal agreements or valid evidence.
Supporting Parties:
Former accountants who mishandled their responsibilities and submitted incorrect or misleading documents.
A previous lawyer who failed to properly defend my case, resulting in legal errors that weakened my position.
Other individuals involved in submitting forged documents or exerting unlawful pressure.
2. Methods of Financial Exploitation:

Partnership Fraud:
Falsely claiming partnership in my private company ("Al-Malik") without fulfilling the payment agreement.
Transferring the company’s address without my knowledge to a location that is supposed to be my shop, to strengthen the false partnership claim.
Unauthorized Money Transfers:
The other party withdrew €48,000 from my bank account using forged documents, while the frozen amount was €110,000.
Before the court session, they returned only €55,000 and kept the remaining funds.
Document Forgery:
Submitting forged documents claiming to be a partner in my companies, including Chamber of Commerce records and rental agreements.
Using my bank accounts to create additional accounts or conduct transactions without my consent.
Pressure and Coercion:
Direct and indirect threats aimed at forcing me to relinquish my property, such as pressuring me to leave my house or shut down my companies.
Recorded videos of threats and assaults on my shop by the other party with four individuals.
Theft of Goods:
Theft of a container containing personal and business goods, including accessories for my BMW, causing substantial financial losses.
3. Financial and Psychological Impacts:

Significant Financial Losses:
Large amounts of money were lost due to unauthorized withdrawals and theft of goods.
My business operations were disrupted due to shop closure and lack of access to my funds.
Psychological and Health Stress:
Constant threats affecting my personal and family stability.
Loss of trust in the legal system due to the unfair handling of my case.
Family Instability:
Threats of eviction without any clear alternatives or plans.
Inability to provide for my children's essential needs due to financial strain.
4. Evidence Available:

Video and audio recordings documenting threats and pressure from the other party.
Legal documents proving my sole ownership of my companies (rental agreements, Chamber of Commerce records, bank cards).
Forged invoices presented by the other party to the court.
Financial evidence showing unauthorized withdrawals from my account.
Video recordings of a meeting where I was forced to make unlawful decisions.
5. My Demands:

Recover all funds withdrawn illegally.
Hold the other party accountable, including anyone involved in forgery and exploitation.
Dismiss any false claims of partnership or ownership by the other party.
Protect my legal rights and restore stability to my family.
Stop all threats or illegal actions being taken against me.
6. Next Steps:

Submit video recordings of the meetings documenting the unlawful decisions.
File a lawsuit to prove the forgery and seek compensation for damages.
Request a comprehensive investigation into my case, providing all relevant documents and evidence.

**Comment by bader1000** [comment]
The Financial Exploitation I Am Experiencing:
1. Individuals or Parties Responsible for the Exploitation:

Primary Party: My cousin, who falsely claims to be a partner in my companies (e.g., "Al-Malik") without any legal agreements or valid evidence.
Supporting Parties:
Former accountants who mishandled their responsibilities and submitted incorrect or misleading documents.
A previous lawyer who failed to properly defend my case, resulting in legal errors that weakened my position.
Other individuals involved in submitting forged documents or exerting unlawful pressure.
2. Methods of Financial Exploitation:

Partnership Fraud:
Falsely claiming partnership in my private company ("Al-Malik") without fulfilling the payment agreement.
Transferring the company’s address without my knowledge to a location that is supposed to be my shop, to strengthen the false partnership claim.
Unauthorized Money Transfers:
The other party withdrew €48,000 from my bank account using forged documents, while the frozen amount was €110,000.
Before the court session, they returned only €55,000 and kept the remaining funds.
Document Forgery:
Submitting forged documents claiming to be a partner in my companies, including Chamber of Commerce records and rental agreements.
Using my bank accounts to create additional accounts or conduct transactions without my consent.
Pressure and Coercion:
Direct and indirect threats aimed at forcing me to relinquish my property, such as pressuring me to leave my house or shut down my companies.
Recorded videos of threats and assaults on my shop by the other party with four individuals.
Theft of Goods:
Theft of a container containing personal and business goods, including accessories for my BMW, causing substantial financial losses.
3. Financial and Psychological Impacts:

Significant Financial Losses:
Large amounts of money were lost due to unauthorized withdrawals and theft of goods.
My business operations were disrupted due to shop closure and lack of access to my funds.
Psychological and Health Stress:
Constant threats affecting my personal and family stability.
Loss of trust in the legal system due to the unfair handling of my case.
Family Instability:
Threats of eviction without any clear alternatives or plans.
Inability to provide for my children's essential needs due to financial strain.
4. Evidence Available:

Video and audio recordings documenting threats and pressure from the other party.
Legal documents proving my sole ownership of my companies (rental agreements, Chamber of Commerce records, bank cards).
Forged invoices presented by the other party to the court.
Financial evidence showing unauthorized withdrawals from my account.
Video recordings of a meeting where I was forced to make unlawful decisions.
5. My Demands:

Recover all funds withdrawn illegally.
Hold the other party accountable, including anyone involved in forgery and exploitation.
Dismiss any false claims of partnership or ownership by the other party.
Protect my legal rights and restore stability to my family.
Stop all threats or illegal actions being taken against me.
6. Next Steps:

Submit video recordings of the meetings documenting the unlawful decisions.
File a lawsuit to prove the forgery and seek compensation for damages.
Request a comprehensive investigation into my case, providing all relevant documents and evidence.
Baderdahannn@gmail.com
Rechtbank Utrecht 
Vijfheerenlanden,vianen
Nederlandse 
Nederland 
Allemaal Nederland
